mangawebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticationapp.urls')),
    path('post/', include('postapp.urls')),
    # path('comment_like/',include("commentlikeapp.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postapp/urls.py
from django.urls import path
from postapp import views



urlpatterns = [
    path('post_view/',views.post_view, name='posts'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit'),
    path('manga/<int:post_id>/', views.manga_detail, name='post_detail'),
    path('reviews/<int:rating_id>/comment/', views.add_comment_to_review, name='add_comment_to_review'),
    path("like/<int:rating_id>/", views.like_view, name='like_post'),
    path('genre/<str:genre>/', views.genre_posts, name='genre_posts'),
    path('follow/<str:username>/', views.follow, name='follow'),
    path('send_friend_request/<str:username>/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('cancel-friend-request/<int:request_id>/', views.cancel_friend_request, name='cancel_friend_request'),
    path('reject_friend_request/<int:request_id>/', views.reject_friend_request, name='reject_friend_request'),
    path('search/', views.search_view, name='search'),
]

authenticationapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ProfileUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(default='profile_pictures/default.jpg' ,upload_to='profile_pictures/', null=True, blank=True)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)

    def __str__(self):
        return self.user.username + "'s Profile"

templates/authentication/changepassword.html
{% extends 'authentication/index.html' %}
{% load static %}
{% block title %}
  <title>Change password</title>
{% endblock %}
{% block content %}
  <main>
    <div class="password-form-container">
      <form method="post">
        {% csrf_token %}
        {% for fm in form %}
          <div class="form-group">{{ fm.label_tag }}{{ fm }} {{ fm.errors|striptags }}</div>
        {% endfor %}
        <button type="submit">Submit</button>
        {% include 'alerts.html' %}
      </form>
    </div>
  </main>
{% endblock %}

templates/authentication/index.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
      <title>Home</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  </head>
  <body>
    <header>
      <div class="header-container">
        <div id="logo-div">
          <h1><a href="{% url 'home' %}"><h1>MangaWeebs</h1></a></h1>
        </div>
        <nav class="navbar">
          <button class="close-btn">X</button>
          <ul>
            <li>
              <a href="{% url 'home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">Home</a>
            </li>
            {% if user.is_authenticated %}
              <li>
                <a href="{% url 'profile' request.user.username %}" class="{% if request.resolver_match.url_name == 'profile_view' %}active{% endif %}">profile</a>
              </li>
              <li>
                <a href="{% url 'posts' %}" class="{% if request.resolver_match.url_name == 'posts' %}active{% endif %}">Create post</a>
              </li>
              <li>
                <a href="{% url 'logout' %}" class="{% if request.resolver_match.url_name == 'logout' %}active{% endif %}">Log Out</a>
              </li>
            {% else %}
              <li>
                <a href="{% url 'login' %}" class="{% if request.resolver_match.url_name == 'login' %}active{% endif %}">Log In</a>
              </li>
              <li>
                <a href="{% url 'login' %}">post</a>
              </li>
            {% endif %}
          </ul>
        </nav>
        <button class="menu-btn">☰</button>
      </div>
    </header>
    {% block content %}
      <div class="search-div">
        <div class="search-container">
          <form method="post" action="{% url 'search' %}">
            {% csrf_token %}
            <input type="text" placeholder="Search by title" name="search" />
            <button type="submit">Search</button>
          </form>
        </div>
        <div>
          <ul class="genre-list">
            {% for genre in genres %}
              <li>
                <button><a href="{% url 'genre_posts' genre %}">{{ genre }}</a></button>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <main>
        <section class="section-home-container">
          <div class="aside-container">
            <h2>Welcome to home page</h2>
            <hr />
            <div class="image-gallery">
              {% for image in images %}
                <div class="image-item">
                  <a href="{% url 'post_detail' image.id %}">
                    <img class="profile-image" src="{{ image.photo.url }}" alt="Post Image" />
                    <p>{{ image.title }}</p>
                  </a>
                </div>
              {% endfor %}
            </div>
          </div>
        </section>
      </main>
    {% endblock %}
    <script src="{% static 'js/home.js' %}"></script>
  </body>
</html>

templates/authentication/login.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Log in</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  </head>
  <body>
    <header>
      <div class="header-container">
        <div id="logo-div">
          <h1><a href="{% url 'home' %}"><h1>MangaWeebs</h1></a></h1>
        </div>
        <nav class="navbar">
          <ul>
            <li>
              <a href="{% url 'home' %}">Home</a>
            </li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="login-container">
      <form method="post">
        {% csrf_token %}
        {% for fm in form %}
          {{ fm.label_tag }}{{ fm }}
          <div class="errors">
            {{ fm.errors|striptags }} <br />
          </div>
        {% endfor %}
        {% if form.non_field_errors %}
          {% for errors in form.non_field_errors %}
            <span class="errors">{{ errors }}</span>
          {% endfor %}
        {% endif %}
        <button>Login</button>
      </form>
      <button class="signup-button"><a href="{% url 'signup' %}">signup</a></button>
      {% include 'alerts.html' %}
    </div>
  </body>
  <script src="{% static 'js/home.js' %}"></script>
</html>

templates/authentication/profile.html
{% extends 'authentication/index.html' %}

{% load static %}

{% block title %}
  <title>Profile</title>
  <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  <link rel="stylesheet" href="{% static 'css/post.css' %}" />
{% endblock %}

{% block content %}
  <div class="profile-view-container">
    <div class="profile-view">
      <div class="profile-div">
        <div class="profile-header">
          <img class="profile-picture" src="{{ profile_details.profile_picture.url }}" alt="{{ profile_user.username }}'s profile picture" />
          <h1>{{ profile_user.username }}</h1>
        </div>
        <div class="profile-details">
          <p>
            <strong>Gender:</strong> {{ profile_details.get_gender_display }}
          </p>
          <p>
            <strong>Followers:</strong> {{ followers_count }}
          </p>
          <p>
            <strong>Following:</strong> {{ following_count }}
          </p>
          {% if is_own_profile %}
            <button class="open-modal"><a href="{% url 'profile_edit' %}">Edit Profile</a></button>
          {% endif %}
          <div class="friend-requests">
            {% if not is_own_profile and not are_friends %}
              {% if friend_request_sent %}
                <form action="{% url 'cancel_friend_request' friend_request_sent.id %}" method="post" class="friend-request-form">
                  {% csrf_token %}
                  <button type="submit" class="cancel">Cancel Friend Request</button>
                </form>
              {% else %}
                <form action="{% url 'send_friend_request' profile_user.username %}" method="post" class="friend-request-form">
                  {% csrf_token %}
                  <button type="submit" class="ok">Send Friend Request</button>
                </form>
              {% endif %}
            {% endif %}
            {% if is_own_profile %}
              {% if friend_request_received %}
              <p>Friend request send by {{friend_request_received.from_user.username}}</p>
                <form action="{% url 'accept_friend_request' friend_request_received.id %}" method="post" class="friend-request-form">
                  {% csrf_token %}
                  <button type="submit" class="ok">Accept Friend Request</button>
                </form>
                <form action="{% url 'reject_friend_request' friend_request_received.id %}" method="post" class="friend-request-form">
                  {% csrf_token %}
                  <button type="submit" class="cancel">Reject Friend Request</button>
                </form>
              {% endif %}
            {% endif %}
          </div>
          {% if request.user != profile_user %}
            {% if is_following %}
              <form action="{% url 'follow' profile_user.username %}" method="post">
                {% csrf_token %}
                <button class="unfollow follow-button" type="submit">Unfollow</button>
              </form>
            {% else %}
              <form action="{% url 'follow' profile_user.username %}" method="post">
                {% csrf_token %}
                <button class="follow follow-button" type="submit">Follow</button>
              </form>
            {% endif %}
          {% endif %}
        </div>
      </div>
      <div class="friends-list">
        <h2>Friends</h2>
        <hr />
        <ul>
          {% for friend in friends %}
            <li>
              <a href="{% url 'profile' friend.username %}">{{ friend.username }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <hr />
    <div class="profile-images">
      {% for image in images %}
        <div class="images-data">
          <div>
            <a href="{% url 'post_detail' image.id %}">
              <img src="{{ image.photo.url }}" alt="{{ image.title }}" /><br />
              <h3>{{ image.title }}</h3>
            </a>
            {% if is_own_profile %}
              <div class="edit-post">
                <form action="{% url 'delete' image.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="delete-button">Delete</button>
                </form>
                <button><a href="{% url 'edit' image.id %}" class="edit-button">Edit</a></button>
              </div>
            {% endif %}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/authentication/profile_edit.html
{% extends 'authentication/index.html' %}
{% load static %}
{% block title %}
  <title>Profile Edit</title>
{% endblock %}

{% block content %}
  <div class="main-container">
    <section class="profile-form-container">
      <h2>Edit Profile:</h2>
      <div class="profile-image-follow">
        {% if profile_form.instance.profile_picture %}
          <img class="profile-picture" src="{{ profile_form.instance.profile_picture.url }}" alt="Profile Picture" />
        {% else %}
          <!-- Display the default profile picture from the media path -->
          <img class="profile-picture" src="/media/profile_pictures/default.jpg" alt="Default Profile Picture" />
        {% endif %}
      <hr />
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for fm in profile_form %}
          <label class="profile-label">{{ fm.label_tag }}</label>
          {{ fm }}
          <div class="profile-error">{{ fm.errors|striptags }}</div>
        {% endfor %}
        {% for fm in user_form %}
          <label class="profile-label">{{ fm.label_tag }}</label>
          {{ fm }}
          <div class="profile-error">{{ fm.errors|striptags }}</div>
        {% endfor %}

        <button type="submit" class="profile-submit-button">Save changes</button>
        <button><a href="{% url 'changepassword' %}">change password with old password</a></button>
      </form>
      {% include 'alerts.html' %}
    </section>
  </div>
{% endblock %}

templates/authentication/signup.html
{% extends 'authentication/index.html' %}
{% load static %}
{% block title %}
  <title>Signup</title>
{% endblock %}
{% block content %}
  <div class="signup-container">
    <form method="post" novalidate>
      {% csrf_token %}
      {% for fm in form %}
        {{ fm.label_tag }}{{ fm }} <div class="errors">{{ fm.errors|striptags }} <br /></div>
      {% endfor %}
      <button>Signup</button>
    </form>
    {% include 'alerts.html' %}
  </div>
{% endblock %}